debug:
  verbose: true

server:
  listen: 7004

  index: control/petri.md

  page:
    title: Loopin Petri Dish
    nav:
      - title: Petri
        page: control/petri.md

      - title: Utility
        page: control/utility.md

  # This is the file that will store persistence for
  # your application.
  persist: data/persist.yaml

  # These directories will be shared under:
  #   http://localhost/files/*
  dirs:
    - control
    - preset
    - shader
    - image
    - data
